### ISSUE TITLE
Literature review

### ISSUE THREAD

**Issue by raspstephan** [raspstephan/nwp-downscale#5]
A place to collect relevant literature.

**To do**
- [x] ESRGAN: http://arxiv.org/abs/1809.00219
- [x] Leinonen 2020: http://arxiv.org/abs/2005.10374

**Comment by raspstephan** [comment]
**Watson et al. 2020 (IBM): Investigating two super-resolution methods for downscaling precipitation: ESRGAN and CAR**

https://www.climatechange.ai/papers/neurips2020/59/paper.pdf

Data: 
- WRF 9km to 3km or 1km. 3 years (80/20 split) at particular location
- Question: At which time are the forecasts matched? Or is it one long continuous run?

Method: 
- ESRGAN with some changes (TO DO: Read paper)
- Content Adaptive Resampler (CAR)
- Question: How large are input/output patches?

Results:
- Really good results with some underestimation of precip.

They also suggest doing GFS 25km to WRF 1km which is pretty similar to what we want to attempt. 

![image](https://user-images.githubusercontent.com/2786927/101656335-de7e3e00-3a42-11eb-8df7-bf00ddad5513.png)

**Comment by raspstephan** [comment]
**Manepalli et al. 2020: GENERALIZATION PROPERTIES OF MACHINE LEARNING BASED WEATHER MODEL DOWNSCALING**

https://ai4earthscience.github.io/iclr-2020-workshop/papers/ai4earth25.pdf

ESRGAN for wind fields without VGG modules

WRF dataset 16/8km to 2km

![image](https://user-images.githubusercontent.com/2786927/101679291-72f69980-3a5f-11eb-80fb-378914b1aea1.png)

**Comment by raspstephan** [comment]
@HirtM I think the most relevant papers to start with are Leinonen 2020 and Watson 2020. There is also the ecPoint paper (http://arxiv.org/abs/2003.14397) which isn't quite the same problem but could hold a lot of valuable lessons for us.

**Comment by HirtM** [comment]
> 
> 
> @HirtM I think the most relevant papers to start with are Leinonen 2020 and Watson 2020. There is also the ecPoint paper (http://arxiv.org/abs/2003.14397) which isn't quite the same problem but could hold a lot of valuable lessons for us.

Perfect, thanks! Just read through the Leinonen 2020 Paper. Here are some key points that I took from it:  

 **Summary:** 
- Downscaling of radar-precip over Switzerland and cloud optical thickness from satellite observations
- They also use an RNN in their GAN so that the output evolves in time in  a consistent manner (they use 10 min intervals). (Maybe this is not as important for us if we use 6h accumulated data)
- There seems to be some variability in their generated ensembles, which makes me optimistic that this could work!

**Key differences to what we plan:** 
- They use coarse grained radar/satellite data as input, while we plan to use coarse-resolution ensembles 
- They have used CRPS, RMSE, etc, but not FSS, which might be important for the spatial information! 
- They are comparing their GAN to other downscaling methods, but not to numerical models

**Comment by raspstephan** [comment]
> They also use an RNN in their GAN so that the output evolves in time in a consistent manner (they use 10 min intervals). (Maybe this is not as important for us if we use 6h accumulated data)

I think eventually we definitely want to be temporally consistent. This is important for flood forecasting etc. But that adds complexity, so I would start with just a single time step as output. We can still put several time slice in the input but just as different channels rather than with an RNN.

> There seems to be some variability in their generated ensembles, which makes me optimistic that this could work!

Certainly true. I talked to Jussi L. He said it was crucial to only have the GAN loss rather than e.g. an additional MSE loss.

> They have used CRPS, RMSE, etc, but not FSS, which might be important for the spatial information!

At some point we should do a review of which metrics are commonly used to evaluate CRMs.
